# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window_view.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QDockWidget, QHBoxLayout, QHeaderView,
    QMainWindow, QMenu, QMenuBar, QSizePolicy,
    QSplitter, QStatusBar, QToolBar, QTreeWidget,
    QTreeWidgetItem, QVBoxLayout, QWidget)

class Ui_MainWindowView(object):
    def setupUi(self, MainWindowView):
        if not MainWindowView.objectName():
            MainWindowView.setObjectName(u"MainWindowView")
        MainWindowView.resize(924, 825)
        MainWindowView.setStyleSheet(u"/*\n"
"QMainWindow::separator{\n"
"    width: 3px;\n"
"    height: 3px;\n"
"}\n"
"*/")
        self.actionNew_Projcect = QAction(MainWindowView)
        self.actionNew_Projcect.setObjectName(u"actionNew_Projcect")
        self.actionOpen_Project = QAction(MainWindowView)
        self.actionOpen_Project.setObjectName(u"actionOpen_Project")
        self.actionRecent_Project = QAction(MainWindowView)
        self.actionRecent_Project.setObjectName(u"actionRecent_Project")
        self.actionSave_Projcet = QAction(MainWindowView)
        self.actionSave_Projcet.setObjectName(u"actionSave_Projcet")
        self.actionSave_As_Project = QAction(MainWindowView)
        self.actionSave_As_Project.setObjectName(u"actionSave_As_Project")
        self.actionClose_Project = QAction(MainWindowView)
        self.actionClose_Project.setObjectName(u"actionClose_Project")
        self.actionExit = QAction(MainWindowView)
        self.actionExit.setObjectName(u"actionExit")
        self.actionProperties = QAction(MainWindowView)
        self.actionProperties.setObjectName(u"actionProperties")
        self.actionAbout = QAction(MainWindowView)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionHelp = QAction(MainWindowView)
        self.actionHelp.setObjectName(u"actionHelp")
        self.actionSetting = QAction(MainWindowView)
        self.actionSetting.setObjectName(u"actionSetting")
        self.actionProperties_2 = QAction(MainWindowView)
        self.actionProperties_2.setObjectName(u"actionProperties_2")
        self.actionCommand = QAction(MainWindowView)
        self.actionCommand.setObjectName(u"actionCommand")
        self.centralwidget = QWidget(MainWindowView)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_main = QVBoxLayout(self.centralwidget)
        self.verticalLayout_main.setObjectName(u"verticalLayout_main")
        self.verticalLayout_main.setContentsMargins(0, 0, 0, 0)
        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Orientation.Vertical)
        self.layoutWidget = QWidget(self.splitter)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.verticalLayout_vtk = QVBoxLayout(self.layoutWidget)
        self.verticalLayout_vtk.setObjectName(u"verticalLayout_vtk")
        self.verticalLayout_vtk.setContentsMargins(0, 0, 0, 0)
        self.splitter.addWidget(self.layoutWidget)
        self.horizontalLayoutWidget = QWidget(self.splitter)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayout_clients = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_clients.setObjectName(u"horizontalLayout_clients")
        self.horizontalLayout_clients.setContentsMargins(0, 0, 0, 0)
        self.splitter.addWidget(self.horizontalLayoutWidget)

        self.verticalLayout_main.addWidget(self.splitter)

        MainWindowView.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindowView)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 924, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuSolver = QMenu(self.menubar)
        self.menuSolver.setObjectName(u"menuSolver")
        self.menuAnalysis = QMenu(self.menubar)
        self.menuAnalysis.setObjectName(u"menuAnalysis")
        self.menuCrowd = QMenu(self.menubar)
        self.menuCrowd.setObjectName(u"menuCrowd")
        self.menuReport = QMenu(self.menubar)
        self.menuReport.setObjectName(u"menuReport")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuWindow = QMenu(self.menubar)
        self.menuWindow.setObjectName(u"menuWindow")
        MainWindowView.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindowView)
        self.statusbar.setObjectName(u"statusbar")
        font = QFont()
        font.setPointSize(10)
        self.statusbar.setFont(font)
        MainWindowView.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindowView)
        self.toolBar.setObjectName(u"toolBar")
        MainWindowView.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.dockWidget_settings = QDockWidget(MainWindowView)
        self.dockWidget_settings.setObjectName(u"dockWidget_settings")
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        self.dockWidget_settings.setFont(font1)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.verticalLayout = QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.treeWidget = QTreeWidget(self.dockWidgetContents)
        self.treeWidget.setObjectName(u"treeWidget")
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(False)
        font2.setItalic(False)
        self.treeWidget.setFont(font2)
        self.treeWidget.setStyleSheet(u"")
        self.treeWidget.setAlternatingRowColors(False)
        self.treeWidget.setAnimated(True)
        self.treeWidget.header().setVisible(False)

        self.verticalLayout.addWidget(self.treeWidget)

        self.dockWidget_settings.setWidget(self.dockWidgetContents)
        MainWindowView.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.dockWidget_settings)
        self.dockWidget_command = QDockWidget(MainWindowView)
        self.dockWidget_command.setObjectName(u"dockWidget_command")
        self.dockWidget_command.setFont(font1)
        self.dockWidgetContents_command = QWidget()
        self.dockWidgetContents_command.setObjectName(u"dockWidgetContents_command")
        self.verticalLayout_command = QVBoxLayout(self.dockWidgetContents_command)
        self.verticalLayout_command.setObjectName(u"verticalLayout_command")
        self.dockWidget_command.setWidget(self.dockWidgetContents_command)
        MainWindowView.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.dockWidget_command)
        self.dockWidget_properties = QDockWidget(MainWindowView)
        self.dockWidget_properties.setObjectName(u"dockWidget_properties")
        self.dockWidget_properties.setFont(font1)
        self.dockWidget_properties.setAllowedAreas(Qt.DockWidgetArea.AllDockWidgetAreas)
        self.dockWidgetContents_properties = QWidget()
        self.dockWidgetContents_properties.setObjectName(u"dockWidgetContents_properties")
        self.verticalLayout_properties = QVBoxLayout(self.dockWidgetContents_properties)
        self.verticalLayout_properties.setObjectName(u"verticalLayout_properties")
        self.dockWidget_properties.setWidget(self.dockWidgetContents_properties)
        MainWindowView.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.dockWidget_properties)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSolver.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.menubar.addAction(self.menuCrowd.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew_Projcect)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_Project)
        self.menuFile.addAction(self.actionRecent_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Projcet)
        self.menuFile.addAction(self.actionSave_As_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionProperties)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuWindow.addAction(self.actionSetting)
        self.menuWindow.addAction(self.actionProperties_2)
        self.menuWindow.addAction(self.actionCommand)

        self.retranslateUi(MainWindowView)

        QMetaObject.connectSlotsByName(MainWindowView)
    # setupUi

    def retranslateUi(self, MainWindowView):
        MainWindowView.setWindowTitle(QCoreApplication.translate("MainWindowView", u"MainWindow", None))
        self.actionNew_Projcect.setText(QCoreApplication.translate("MainWindowView", u"New...", None))
        self.actionOpen_Project.setText(QCoreApplication.translate("MainWindowView", u"Open...", None))
        self.actionRecent_Project.setText(QCoreApplication.translate("MainWindowView", u"Recent", None))
        self.actionSave_Projcet.setText(QCoreApplication.translate("MainWindowView", u"Save", None))
        self.actionSave_As_Project.setText(QCoreApplication.translate("MainWindowView", u"Save As...", None))
        self.actionClose_Project.setText(QCoreApplication.translate("MainWindowView", u"Close", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindowView", u"Quit", None))
        self.actionProperties.setText(QCoreApplication.translate("MainWindowView", u"Preferences...", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindowView", u"About...", None))
        self.actionHelp.setText(QCoreApplication.translate("MainWindowView", u"Help", None))
        self.actionSetting.setText(QCoreApplication.translate("MainWindowView", u"Setting", None))
        self.actionProperties_2.setText(QCoreApplication.translate("MainWindowView", u"Properties", None))
        self.actionCommand.setText(QCoreApplication.translate("MainWindowView", u"Command", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindowView", u"File", None))
        self.menuSolver.setTitle(QCoreApplication.translate("MainWindowView", u"Hall", None))
        self.menuAnalysis.setTitle(QCoreApplication.translate("MainWindowView", u"Solver", None))
        self.menuCrowd.setTitle(QCoreApplication.translate("MainWindowView", u"Crowd", None))
        self.menuReport.setTitle(QCoreApplication.translate("MainWindowView", u"Report", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindowView", u"Help", None))
        self.menuWindow.setTitle(QCoreApplication.translate("MainWindowView", u"Window", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindowView", u"toolBar", None))
        self.dockWidget_settings.setWindowTitle(QCoreApplication.translate("MainWindowView", u"Settings", None))
        ___qtreewidgetitem = self.treeWidget.headerItem()
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("MainWindowView", u"\uc124\uc815", None));
        self.dockWidget_command.setWindowTitle(QCoreApplication.translate("MainWindowView", u"Run", None))
        self.dockWidget_properties.setWindowTitle(QCoreApplication.translate("MainWindowView", u"Properties", None))
    # retranslateUi

